
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { CustomDatabase } from '@/types/supabase';
import { AppUser, ProfileData } from '@/types';

const SUPABASE_URL = "https://api.supabase.mbtool.online";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4aGF3dG5ka3ViYWVsamJheWxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTkxMTEsImV4cCI6MjA2MDk3NTExMX0.9hsOts4HHM4tvqp5JkESOLuAJLHNYOsME7O4ekOq4oE";

export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});

// Helper function to create a first admin user
export async function createFirstAdminIfNeeded(email: string, password: string, name: string) {
  try {
    // Check if there are any users first
    const { data, error: countError } = await supabase
      .from('profiles')
      .select('*', { count: 'exact', head: true })
      .in('schema', ['login_project']);
    
    if (countError) {
      console.error('Error checking for users:', countError);
      return;
    }
    
    // If no users exist, create the first admin
    if (data?.length === 0) {
      const { data: authData, error } = await supabase.auth.signUp({
        email,
        password,
        options: {
          data: {
            name,
          },
        }
      });
      
      if (error) {
        console.error('Error creating first admin:', error);
        return;
      }
      
      // Update the user's role to admin
      if (authData.user) {
        await supabase
          .from('profiles')
          .update({ role: 'admin' })
          .eq('id', authData.user.id)
          .in('schema', ['login_project']);
      }
      
      console.log('First admin user created successfully!');
    }
  } catch (error) {
    console.error('Error in createFirstAdminIfNeeded:', error);
  }
}
